export const CHANGE_ACTIVE_FOLDER = "CHANGE_FOLDER";
export const SET_DEFAULT_FOLDERS = "SET_DEFAULT_FOLDERS";

export const SHOW_ADD_MODAL = "SHOW_ADD_MODAL";
export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const CHANGE_INPUT_MODAL = "CHANGE_INPUT_MODAL";

export const GET_USER_FOLDERS_REQ = "GET_USER_FOLDERS_REQ";
export const GET_USER_FOLDERS_ERROR = "GET_USER_FOLDERS_ERROR";
export const GET_USER_FOLDERS_SUCCESS = "GET_USER_FOLDERS_SUCCESS";

export const REMOVE_USER_FOLDER_SUCCESS = "REMOVE_USER_FOLDER_SUCCESS";
export const SHOW_SUBMENU = "SHOW_SUBMENU";

export const GET_MESSAGES_REQ = "GET_MESSAGES_REQ";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";

export const GET_MAIL_REQ = "GET_MAIL_REQ";
export const GET_MAIL_ERROR = "GET_MAIL_ERROR";
export const GET_MAIL_SUCCESS = "GET_MAIL_SUCCESS";
export const EDIT_MAIL_STATUS = "EDIT_MAIL_STATUS";