export const CHANGE_ACTIVE_FOLDER = "CHANGE_FOLDER";
export const GET_MESSAGES = "GET_MESSAGES";
export const SET_DEFAULT_FOLDERS = "SET_DEFAULT_FOLDERS";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
export const CHANGE_INPUT_EDIT = "CHANGE_INPUT_EDIT";

export const GET_USER_FOLDERS_REQ = "GET_USER_FOLDERS_REQ";
export const GET_USER_FOLDERS_ERROR = "GET_USER_FOLDERS_ERROR";
export const GET_USER_FOLDERS_SUCCESS = "GET_USER_FOLDERS_SUCCESS";